server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: book-service

  datasource:
    url: jdbc:postgresql://localhost:5454/book_db
    username: postgres
    password: mysecretpassword

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379
    password:
    cache-ttl: 10m

  cache:
    type: redis

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: book-service-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"