spring:
  application:
    name: booksAPI

  datasource:
    url: jdbc:postgresql://localhost:5454/postgres
    username: postgres
    password: mysecretpassword

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379
    password:
    cache-ttl: 10m

  cache:
    type: redis